SET IDENTITY_INSERT [dbo].[AUTOR] ON
INSERT INTO [dbo].[AUTOR] ([Id], [NOME]) VALUES (1, N'PAULO COELHO')
INSERT INTO [dbo].[AUTOR] ([Id], [NOME]) VALUES (2, N'ZE')
INSERT INTO [dbo].[AUTOR] ([Id], [NOME]) VALUES (3, N'AUGUSTO CURY')
INSERT INTO [dbo].[AUTOR] ([Id], [NOME]) VALUES (4, N'APRIGIO')
SET IDENTITY_INSERT [dbo].[AUTOR] OFF
