SET IDENTITY_INSERT [dbo].[PRODUTO] ON
INSERT INTO [dbo].[PRODUTO] ([Id], [NOME], [UNIDADE], [VALOR]) VALUES (1, N'BANANA', N'KG', CAST(5 AS Decimal(18, 0)))
INSERT INTO [dbo].[PRODUTO] ([Id], [NOME], [UNIDADE], [VALOR]) VALUES (2, N'LARANJA', N'KG', CAST(7 AS Decimal(18, 0)))
INSERT INTO [dbo].[PRODUTO] ([Id], [NOME], [UNIDADE], [VALOR]) VALUES (3, N'FEIJAO', N'KG', CAST(8 AS Decimal(18, 0)))
INSERT INTO [dbo].[PRODUTO] ([Id], [NOME], [UNIDADE], [VALOR]) VALUES (4, N'COCA-COLA', N'LITRO', CAST(5 AS Decimal(18, 0)))
SET IDENTITY_INSERT [dbo].[PRODUTO] OFF
