CREATE TABLE [dbo].[PEDIDO]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[DATA_PEDIDO] DATE NULL,
	[QUANITDADE] INT  NULL,
	[PRODUTOID] INT NOT NULL,
	[CLIENTEID] INT NOT NULL,
	FOREIGN KEY [][dbo].[PRODUTO].[NOME]

	 
)
