SET IDENTITY_INSERT [dbo].[Table] ON
INSERT INTO [dbo].[Table] ([Id], [NOME], [EMAIL], [TELEFONE], [ALTURA], [APROVADO]) VALUES (1, N'APRIGIO', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [NOME], [EMAIL], [TELEFONE], [ALTURA], [APROVADO]) VALUES (2, N'LUIZ', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [NOME], [EMAIL], [TELEFONE], [ALTURA], [APROVADO]) VALUES (3, N'FCDFDL', NULL, NULL, NULL, NULL)
INSERT INTO [dbo].[Table] ([Id], [NOME], [EMAIL], [TELEFONE], [ALTURA], [APROVADO]) VALUES (4, N'hahahahaha', NULL, NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Table] OFF
